[package]
name = "mzsignal"
version = "0.2.4"
edition = "2021"

keywords = [
    'mass-spectrometry',
    'signal-processing',
    'peak-picking'
]

categories = [
    "science"
]

description = "A library for mass spectrometry signal processing"
license = "Apache-2.0"
repository = "https://github.com/mobiusklein/mzsignal"
documentation = "https://docs.rs/mzsignal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mzsignal"
src = "src/lib.rs"

[profile.release]
lto = true

# local dependency crate
[features]
default = ["intel-mkl", "parallelism"]
openblas = ["ndarray-linalg/openblas-static"]
netlib = ["ndarray-linalg/netlib"]
intel-mkl = ["ndarray-linalg/intel-mkl-static"]
parallelism = ["rayon"]

plotting = ["plotters"]

[dependencies]
log = "0.4.14"
pretty_env_logger = "0.4.0"
num-traits = "0.2"
ndarray = "0.15.6"
ndarray-linalg = {version = "0.16.0"}
cfg-if = "1.0.0"
rayon = { version = "1.5.1", optional = true }
plotters = { version = "0.3.4", optional = true}
mzpeaks = { version="0.4.0" }

[dev-dependencies]
rstest = "0.10.0"

[package.metadata.docs.rs]
features = ["openblas", "parallelism"]
no-default-features = true

